name: Builds, signs and publishes the WebExtension
on:
  push:
    branches:
      - "!*"
    tags:
      - 'v*'

jobs:
  build:
    name: Build the extension
    runs-on: ubuntu-latest
    steps:
      - name: Pull and checkout source
        uses: actions/checkout@main

      - name: Set IS_RELEASE value
        id: set_is_release
        run: |
         TAG_NAME=$(git describe --tags) && TEMP=`[[ $TAG_NAME =~ "-beta" ]] && echo false || echo true` && echo "IS_RELEASE=$TEMP" >> $GITHUB_ENV
      
      - name: Setup and build extension
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm ci
      - run: npm run build
      - run: npm run update:manifest

      - name: Persist /build between jobs
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build

  publish-to-amo:
    needs: build
    name: Sign and publish extension to firefox addons 
    runs-on: ubuntu-latest
    steps:
      - name: Get /build data
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build

      - name: Copy manifest.json
        run: |
          cp build/manifest.json ./manifest.json

      - name: Sign and publish
        uses: saphareas/sign-web-extension-action@master
        with:
          web-ext-id: "{91bd6831-f5f6-4a56-85e2-67ae48116078}"
          sign-listed: ${{ env.IS_RELEASE }}
          amo-api-key: ${{ secrets.AMO_API_KEY }}
          amo-api-secret: ${{ secrets.AMO_API_SECRET }}
  publish-to-cws:
    needs: build
    name: Sign and publish extension to chrome web store
    runs-on: ubuntu-latest
    steps:
      - name: Get /build data
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build

      - name: Zip extension
        uses: papeloto/action-zip@v1
        with:
          files: build/
          dest: build.zip

      - name: Publish
        uses: Passiverecords/chrome-extension-upload-action@1.4.1
        with:
          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
          client-id: ${{ secrets.CHROME_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          file-name: "build.zip"
          app-id: "ajgamcgebnhahghjlclajdplkbagigch"
          publish: ${{ env.IS_RELEASE }}
  