name: Builds, signs and publishes the WebExtension
on:
  push:
    branches:
      - main

jobs:
  publish-to-amo:
    name: Build and publish the extension
    runs-on: ubuntu-latest
    steps:
      - name: Pull and checkout source
        uses: actions/checkout@main

      - name: Setup and build extension
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm ci
      - run: npm build

      - name: Sign the web-ext
        uses: saphareas/sign-web-extension-action@master
        with:
          web-ext-id: "{91bd6831-f5f6-4a56-85e2-67ae48116078}"
          sign-listed: false
          amo-api-key: ${{ secrets.AMO_API_KEY }}
          amo-api-secret: ${{ secrets.AMO_API_SECRET }}